Update run

diff --git a/.local/bin/run b/.local/bin/run
--- a/.local/bin/run
+++ b/.local/bin/run
@@ -14,17 +14,16 @@ if [ -x "$(command -v apt-get)" ]; then sudo apt-get --yes install $packagesNeed
 elif [ -x "$(command -v dnf)" ];     then sudo dnf install $packagesNeeded
 elif [ -x "$(command -v zypper)" ];  then sudo zypper install $packagesNeeded
 elif [ -x "$(command -v pacman)" ];  then sudo pacman -S $packagesNeeded
-
-else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi
-
-if [ -x "$(command -v pacman)" ] && builtin type -p 'git' >/dev/null 2>&1; then
+elif [ -x "$(command -v pacman)" ] && builtin type -p 'git' >/dev/null 2>&1; then
     echo 'Installing yay and Fastfetch.'
     sudo pacman -S --needed base base-devel wget
     git clone https://aur.archlinux.org/yay.git
     rm -rf ~/yay
      yay -S fastfetch
 
- fi
+else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; 
+fi
+
 echo
 echo
 echo "Pausing to see if there are any Package Manager errors"
