manual scripted

diff --git a/.local/bin/run b/.local/bin/run
--- a/.local/bin/run
+++ b/.local/bin/run
@@ -1,30 +1,33 @@
 #!/bin/bash
 #shopt -s expand_aliases
-##
-## Git, Zsh and Fastfetch(opt. Arch) must be installed
-## The script will attempt to install these packages along with the required fonts
-## Select the MesloLGS font as your terminal font
-## This is the curl command to run the script
-## curl -sL https://bit.ly/3CnJXWo | bash
-## OR
-## curl -sL https://raw.githubusercontent.com/bkmo/.zsh-dotfiles/master/.local/bin/run | bash
+#
+# Git, Zsh and Fastfetch(opt. Arch) must be installed
+# The script will attempt to install these packages along with the required fonts
+# Select the MesloLGS font as your terminal font
+# This is the curl command to run the script
+# curl -sL https://bit.ly/3CnJXWo | bash
+# OR
+# curl -sL https://raw.githubusercontent.com/bkmo/.zsh-dotfiles/master/.local/bin/run | bash
 
-packagesNeeded='git zsh '
+function install { packagesNeeded='git zsh '
 if [ -x "$(command -v apt-get)" ]; then sudo apt-get --yes install $packagesNeeded
 elif [ -x "$(command -v dnf)" ];     then sudo dnf install $packagesNeeded
 elif [ -x "$(command -v zypper)" ];  then sudo zypper install $packagesNeeded
 elif [ -x "$(command -v pacman)" ];  then sudo pacman -S $packagesNeeded
 
-else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi
+else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi }
 
-#if [ -x "$(command -v pacman)" ] && builtin type -p 'git' >/dev/null 2>&1; then
- #   echo 'Installing yay and Fastfetch.'
- #   sudo pacman -S --needed base base-devel wget
- #   git clone https://aur.archlinux.org/yay.git
-  #  rm -rf ~/yay
-   #  yay -S fastfetch
+function ffyay { if [ -x "$(command -v pacman)" ] && builtin type -p 'git' >/dev/null 2>&1; then
+    echo 'Installing yay and Fastfetch.'
+    sudo pacman -S --needed base base-devel wget
+    git clone https://aur.archlinux.org/yay.git
+    rm -rf ~/yay
+    yay -S fastfetch
 
- #fi
+ fi }
+install
+ffyay
+
 echo
 echo
 echo "Pausing to see if there are any Package Manager errors"
