manual scripted

diff --git a/.local/bin/run b/.local/bin/run
--- a/.local/bin/run
+++ b/.local/bin/run
@@ -9,25 +9,14 @@
 # OR
 # curl -sL https://raw.githubusercontent.com/bkmo/.zsh-dotfiles/master/.local/bin/run | bash
 
-function install { packagesNeeded='git zsh '
+packagesNeeded='git zsh '
 if [ -x "$(command -v apt-get)" ]; then sudo apt-get --yes install $packagesNeeded
 elif [ -x "$(command -v dnf)" ];     then sudo dnf install $packagesNeeded
 elif [ -x "$(command -v zypper)" ];  then sudo zypper install $packagesNeeded
-elif [ -x "$(command -v pacman)" ];  then sudo pacman -S $packagesNeeded &
+elif [ -x "$(command -v pacman)" ];  then sudo pacman -S $packagesNeeded
 
-#else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2;
-fi }
-
-function ffyay { if [ -x "$(command -v pacman)" ] && builtin type -p 'git' >/dev/null 2>&1; then
-    echo 'Installing yay and Fastfetch.'
-    sudo pacman -S --needed base base-devel wget
-    git clone https://aur.archlinux.org/yay.git
-    rm -rf ~/yay
-    yay -S fastfetch
-
- fi }
-install
-ffyay
+else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2;
+fi
 
 echo
 echo
@@ -45,8 +34,6 @@ sudo curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%
 sudo curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf --output /usr/share/fonts/MesloLGS/'MesloLGS NF Bold Italic.ttf'
 
 git clone --bare -b master https://github.com/bkmo/.zsh-dotfiles.git $HOME/.zsh-dotfiles
-
-config config --local status.showUntrackedFiles no
 
 echo "alias config='/usr/bin/git --git-dir=$HOME/.zsh-dotfiles/ --work-tree=$HOME'" >> $HOME/.bashrc
 
